"use client";

import { useState } from "react";
import type { ClaimCard, SourceCard, Usage } from "@/lib/events";

export function ReportToolbar({
  question,
  report,
  sources,
  claims,
  usage,
  runId,
  done,
}: {
  question: string;
  report: string;
  sources: SourceCard[];
  claims: ClaimCard[];
  usage: Usage | null;
  runId: string | null;
  done: boolean;
}) {
  const [copied, setCopied] = useState(false);

  const exportMarkdown = () => {
    const md = toMarkdown(question, report, sources, claims);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `synthesis-${runId ?? "report"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyShare = async () => {
    if (!runId) return;
    const link = `${window.location.origin}/run/${runId}`;
    try {
      await navigator.clipboard.writeText(link);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard unavailable */
    }
  };

  return (
    <div className="print-hide flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3 font-mono text-[11px]">
      <div className="flex items-center gap-3 text-faint">
        {usage ? (
          <>
            <span className="text-muted">
              {formatTokens(usage.inputTokens + usage.outputTokens)} tok
            </span>
            <span>·</span>
            <span className="text-muted">${usage.usd.toFixed(4)}</span>
          </>
        ) : (
          <span>metering…</span>
        )}
      </div>
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={exportMarkdown}
          disabled={!report}
          className="rounded border border-border px-2.5 py-1 uppercase tracking-widest text-muted transition-colors hover:bg-surface-2 hover:text-text disabled:opacity-40"
        >
          .md
        </button>
        <button
          type="button"
          onClick={() => window.print()}
          disabled={!report}
          className="rounded border border-border px-2.5 py-1 uppercase tracking-widest text-muted transition-colors hover:bg-surface-2 hover:text-text disabled:opacity-40"
        >
          print
        </button>
        {done && runId ? (
          <button
            type="button"
            onClick={copyShare}
            className="rounded border border-accent/40 bg-accent/10 px-2.5 py-1 uppercase tracking-widest text-accent transition-colors hover:bg-accent/20"
          >
            {copied ? "copied" : "share"}
          </button>
        ) : null}
      </div>
    </div>
  );
}

function formatTokens(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

function toMarkdown(
  question: string,
  report: string,
  sources: SourceCard[],
  claims: ClaimCard[],
): string {
  const lines = [`# ${question}`, "", report, "", "## Sources"];
  for (const s of sources) lines.push(`${s.id}. [${s.title}](${s.url})`);
  if (claims.length > 0) {
    lines.push("", "## Claim verification");
    for (const c of claims) lines.push(`- (${c.confidence}) ${c.text} ${c.sourceIds.map((id) => `[${id}]`).join(" ")}`);
  }
  lines.push("", "_Generated by Synthesis._");
  return lines.join("\n");
}
